# Generated by Django 4.1.1 on 2022-09-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_alter_cart_image_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='owner',
        ),
    ]
