# Generated by Django 4.1.1 on 2022-09-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_billingform_cart_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingform',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
