# Generated by Django 4.1.1 on 2022-09-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_alter_billingform_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingform',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
