# Generated by Django 4.1.1 on 2024-07-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_cart_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='price_naira',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_naira',
        ),
        migrations.AddField(
            model_name='cart',
            name='price_dollar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price_dollar',
            field=models.IntegerField(default=0),
        ),
    ]
