# Generated by Django 4.1.1 on 2024-07-22 20:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransactionStripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=70, null=True)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
    ]
